config/routes.rb
Rails.application.routes.draw do
 resources :continents do
   resources :locations do
    resources :surfcamps, only: [:index,:new, :create, :show]
  end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/continent.rb
class Continent < ApplicationRecord
  has_many :locations
  has_one_attached :photo
  has_many :surfcamps, through: :locations
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :surfcamps
  belongs_to :continent
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/surfcamp.rb
class Surfcamp < ApplicationRecord
  belongs_to :location
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/continents_controller.rb
class ContinentsController < ApplicationController
  def index
   @continents = Continent.all
   @surfcamps =  Surfcamp.geocoded

    @markers = @surfcamps.map do |surfcamp|
      {
        lat: surfcamp.latitude,
        lng: surfcamp.longitude
      }
    end
  end
  def show

  end

   def create
    @continent = Continent.new(review_params)
    @continent.save
    redirect_to continents_path
  end

  def new

  @continent = Continent.new
  end

  def review_params
    params.require(:continent).permit(:name,:description,:photo)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
   @continent = Continent.find(params[:continent_id])
   @locations = Location.where(continent_id: @continent.id)
   # @locations = Location.geocoded

   #  @markers = @locations.map do |location|
   #    {
   #      lat: location.latitude,
   #      lng: location.longitude
   #    }
  end

  def show
    @continent = Continent.find(params[:continent_id])
    @locations = Location.where(continent_id: @continent.id)
    # Another way of filtering results
    # @surfcamps = Surfcamp.where(location_id: @location.id)
  end

  def new
   @continent = Continent.find(params[:continent_id])
   @location = Location.new
  end

  def create
   @continent = Continent.find(params[:continent_id])
   @location = Location.new(review_params)
   @location.continent = @continent
   @location.save
   redirect_to(continents_path)
  end

  def edit

  end

  def update
  @location = Location.find(params[:id])
  @location.update(review_params)
  end

  def destroy

  end

  def review_params
    params.require(:location).permit(:name,:description,:photo,:address)
  end
end

app/controllers/surfcamps_controller.rb
class SurfcampsController < ApplicationController
  def index
    @continent = Continent.find(params[:continent_id])
    @location = Location.find(params[:location_id])
    @surfcamps = Surfcamp.where(location_id: @location.id)
  end

  def show
    @surfcamp = Surfcamp.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def new
   @continent = Continent.find(params[:continent_id])
   @location = Location.find(params[:location_id])
   @surfcamp = Surfcamp.new
  end

  def create
    @continent = Continent.find(params[:continent_id])
    @location = Location.find(params[:location_id])
    @surfcamp = Surfcamp.new(review_params)
    @surfcamp.location = @location
    @surfcamp.save
    redirect_to continent_location_surfcamps_path(@continent,@location)
  end

  def review_params
    params.require(:surfcamp).permit(:name,:stars,:price,:photo,:address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/continents_helper.rb
module ContinentsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/surfcamps_helper.rb
module SurfcampsHelper
end

app/views/continents/index.html.erb
<!DOCTYPE HTML>
<!--
  Helios by HTML5 UP
  html5up.net | @ajlkn
  Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
  <head>
    <title>Surf Camps</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="assets/css/main.css" />
    <noscript><link rel="stylesheet" href="assets/css/noscript.css" /></noscript>
  </head>
  <body class="homepage is-preload">
    <div id="page-wrapper">

      <!-- Header -->
        <div id="header">
          <!-- Inner -->
            <div class="inner">
              <header>
                <h1><a href="index.html" id="logo">Surf Camps</a></h1>
                <hr />
                <p>Let's get it</p>
              </header>
              <footer>
                <%=link_to "Start",new_continent_path ,:class => "button circled scrolly"%>
              </footer>
            </div>

          <!-- Nav -->
            <nav id="nav">
              <ul>
                <li><a href="index.html">Home</a></li>
                <li>
                  <a href="#">Dropdown</a>
                  <ul>
                    <li><a href="#">Lorem ipsum dolor</a></li>
                    <li><a href="#">Magna phasellus</a></li>
                    <li><a href="#">Etiam dolore nisl</a></li>
                    <li>
                      <a href="#">And a submenu &hellip;</a>
                      <ul>
                        <li><a href="#">Lorem ipsum dolor</a></li>
                        <li><a href="#">Phasellus consequat</a></li>
                        <li><a href="#">Magna phasellus</a></li>
                        <li><a href="#">Etiam dolore nisl</a></li>
                      </ul>
                    </li>
                    <li><a href="#">Veroeros feugiat</a></li>
                  </ul>
                </li>
                <li><a href="left-sidebar.html">Left Sidebar</a></li>
                <li><a href="right-sidebar.html">Right Sidebar</a></li>
                <li><a href="no-sidebar.html">No Sidebar</a></li>
              </ul>
            </nav>

        </div>

      <!-- Banner -->
        <section id="banner">
          <header>
            <h2>Hello, Welcome to the best surfing website <strong></strong>.</h2>
            <p>
              A (free) responsive site template by <a href="http://html5up.net">HTML5 UP</a>.
              Built with HTML5/CSS3 and released under the <a href="http://html5up.net/license">CCA</a> license.
            </p>
          </header>
        </section>

      <!-- Carousel -->
        <section class="carousel">
          <div class="reel">
            <%@continents.each do |location| %>
            <article>
              <%if location.photo.attached? %>
              <a href="#" class="image featured"><%=image_tag location.photo, width: 400, height: 300, crop: :fill %></a>
              <%end%>
              <header>
                <%= link_to(continent_locations_path(location)) do %>
            <h3><strong><%=location.name%></strong></h3>
            <% end %>
              </header>
              <p><%=location.description%></p>
            </article>
            <%end%>
          </div>
        </section>
       <div
          id="map"
          style="width: 100%;
          height: 600px;  box-shadow: 0 0.15em 0.25em 0 rgba(0, 0, 0, 0.25);"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
         >

        </div>
      <!-- Main -->
        <div class="wrapper style2">

          <article id="main" class="container special">
            <a href="#" class="image featured"><img src="images/pic06.jpg" alt="" /></a>
            <header>
              <h2><a href="#">Sed massa imperdiet magnis</a></h2>
              <p>
                Sociis aenean eu aenean mollis mollis facilisis primis ornare penatibus aenean. Cursus ac enim
                pulvinar curabitur morbi convallis. Lectus malesuada sed fermentum dolore amet.
              </p>
            </header>
            <p>
              Commodo id natoque malesuada sollicitudin elit suscipit. Curae suspendisse mauris posuere accumsan massa
              posuere lacus convallis tellus interdum. Amet nullam fringilla nibh nulla convallis ut venenatis purus
              sit arcu sociis. Nunc fermentum adipiscing tempor cursus nascetur adipiscing adipiscing. Primis aliquam
              mus lacinia lobortis phasellus suscipit. Fermentum lobortis non tristique ante proin sociis accumsan
              lobortis. Auctor etiam porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum
              consequat integer interdum integer purus sapien. Nibh eleifend nulla nascetur pharetra commodo mi augue
              interdum tellus. Ornare cursus augue feugiat sodales velit lorem. Semper elementum ullamcorper lacinia
              natoque aenean scelerisque.
            </p>
            <footer>
              <a href="#" class="button">Continue Reading</a>
            </footer>
          </article>

        </div>

      <!-- Features -->
        <div class="wrapper style1">

          <section id="features" class="container special">
            <header>
              <h2>Morbi ullamcorper et varius leo lacus</h2>
              <p>Ipsum volutpat consectetur orci metus consequat imperdiet duis integer semper magna.</p>
            </header>
            <div class="row">
              <article class="col-4 col-12-mobile special">
                <a href="#" class="image featured"><img src="images/pic07.jpg" alt="" /></a>
                <header>
                  <h3><a href="#">Gravida aliquam penatibus</a></h3>
                </header>
                <p>
                  Amet nullam fringilla nibh nulla convallis tique ante proin sociis accumsan lobortis. Auctor etiam
                  porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum consequat integer interdum.
                </p>
              </article>
              <article class="col-4 col-12-mobile special">
                <a href="#" class="image featured"><img src="images/pic08.jpg" alt="" /></a>
                <header>
                  <h3><a href="#">Sed quis rhoncus placerat</a></h3>
                </header>
                <p>
                  Amet nullam fringilla nibh nulla convallis tique ante proin sociis accumsan lobortis. Auctor etiam
                  porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum consequat integer interdum.
                </p>
              </article>
              <article class="col-4 col-12-mobile special">
                <a href="#" class="image featured"><img src="images/pic09.jpg" alt="" /></a>
                <header>
                  <h3><a href="#">Magna laoreet et aliquam</a></h3>
                </header>
                <p>
                  Amet nullam fringilla nibh nulla convallis tique ante proin sociis accumsan lobortis. Auctor etiam
                  porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum consequat integer interdum.
                </p>
              </article>
            </div>
          </section>

        </div>

      <!-- Footer -->
        <div id="footer">
          <div class="container">
            <div class="row">

              <!-- Tweets -->
                <section class="col-4 col-12-mobile">
                  <header>
                    <h2 class="icon brands fa-twitter circled"><span class="label">Tweets</span></h2>
                  </header>
                  <ul class="divided">
                    <li>
                      <article class="tweet">
                        Amet nullam fringilla nibh nulla convallis tique ante sociis accumsan.
                        <span class="timestamp">5 minutes ago</span>
                      </article>
                    </li>
                    <li>
                      <article class="tweet">
                        Hendrerit rutrum quisque.
                        <span class="timestamp">30 minutes ago</span>
                      </article>
                    </li>
                    <li>
                      <article class="tweet">
                        Curabitur donec nulla massa laoreet nibh. Lorem praesent montes.
                        <span class="timestamp">3 hours ago</span>
                      </article>
                    </li>
                    <li>
                      <article class="tweet">
                        Lacus natoque cras rhoncus curae dignissim ultricies. Convallis orci aliquet.
                        <span class="timestamp">5 hours ago</span>
                      </article>
                    </li>
                  </ul>
                </section>

              <!-- Posts -->
                <section class="col-4 col-12-mobile">
                  <header>
                    <h2 class="icon solid fa-file circled"><span class="label">Posts</span></h2>
                  </header>
                  <ul class="divided">
                    <li>
                      <article class="post stub">
                        <header>
                          <h3><a href="#">Nisl fermentum integer</a></h3>
                        </header>
                        <span class="timestamp">3 hours ago</span>
                      </article>
                    </li>
                    <li>
                      <article class="post stub">
                        <header>
                          <h3><a href="#">Phasellus portitor lorem</a></h3>
                        </header>
                        <span class="timestamp">6 hours ago</span>
                      </article>
                    </li>
                    <li>
                      <article class="post stub">
                        <header>
                          <h3><a href="#">Magna tempus consequat</a></h3>
                        </header>
                        <span class="timestamp">Yesterday</span>
                      </article>
                    </li>
                    <li>
                      <article class="post stub">
                        <header>
                          <h3><a href="#">Feugiat lorem ipsum</a></h3>
                        </header>
                        <span class="timestamp">2 days ago</span>
                      </article>
                    </li>
                  </ul>
                </section>

              <!-- Photos -->
                <section class="col-4 col-12-mobile">
                  <header>
                    <h2 class="icon solid fa-camera circled"><span class="label">Photos</span></h2>
                  </header>
                  <div class="row gtr-25">
                    <div class="col-6">
                      <a href="#" class="image fit"><img src="images/pic10.jpg" alt="" /></a>
                    </div>
                    <div class="col-6">
                      <a href="#" class="image fit"><img src="images/pic11.jpg" alt="" /></a>
                    </div>
                    <div class="col-6">
                      <a href="#" class="image fit"><img src="images/pic12.jpg" alt="" /></a>
                    </div>
                    <div class="col-6">
                      <a href="#" class="image fit"><img src="images/pic13.jpg" alt="" /></a>
                    </div>
                    <div class="col-6">
                      <a href="#" class="image fit"><img src="images/pic14.jpg" alt="" /></a>
                    </div>
                    <div class="col-6">
                      <a href="#" class="image fit"><img src="images/pic15.jpg" alt="" /></a>
                    </div>
                  </div>
                </section>

            </div>
            <hr />
            <div class="row">
              <div class="col-12">

                <!-- Contact -->
                  <section class="contact">
                    <header>
                      <h3>Nisl turpis nascetur interdum?</h3>
                    </header>
                    <p>Urna nisl non quis interdum mus ornare ridiculus egestas ridiculus lobortis vivamus tempor aliquet.</p>
                    <ul class="icons">
                      <li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
                      <li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
                      <li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
                      <li><a href="#" class="icon brands fa-pinterest"><span class="label">Pinterest</span></a></li>
                      <li><a href="#" class="icon brands fa-dribbble"><span class="label">Dribbble</span></a></li>
                      <li><a href="#" class="icon brands fa-linkedin-in"><span class="label">Linkedin</span></a></li>
                    </ul>
                  </section>

                <!-- Copyright -->
                  <div class="copyright">
                    <ul class="menu">
                      <li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
                    </ul>
                  </div>

              </div>

            </div>
          </div>
        </div>

    </div>

    <!-- Scripts -->
<!--       <script src="assets/js/jquery.min.js"></script>
      <script src="assets/js/jquery.dropotron.min.js"></script>
      <script src="assets/js/jquery.scrolly.min.js"></script>
      <script src="assets/js/jquery.scrollex.min.js"></script>
      <script src="assets/js/browser.min.js"></script>
      <script src="assets/js/breakpoints.min.js"></script>
      <script src="assets/js/util.js"></script>
      <script src="assets/js/main.js"></script> -->

  </body>
</html>

app/views/continents/new.html.erb
<div class="container">
<%= simple_form_for @continent do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%=f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Surfcamps</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/locations/index.html.erb
<%if @continent.photo.attached?%>
<%=image_tag @continent.photo, width: 400, height: 300, crop: :fill, class: "location_banner" %>
<%end%>
<h3 class="location_name"><%=@continent.name%></h3>

<% @locations.each do |location|%>
<div class="card-trip">
  <%if location.photo.attached?%>
  <%=image_tag location.photo, width: 400, height: 300, crop: :fill, class: "img"%>
  <%end%>
  <div class="card-trip-infos">
  <%=link_to continent_location_surfcamps_path(@continent, location) do %>
  <h2><strong><%=location.name.capitalize%></strong></h2>
  <%end%>
</div>
</div>
<%end%>

<div class="text-center">
 <%=link_to "Create new Location",new_continent_location_path(@continent),:class => "button circled scroll"%>
<%=link_to "Go to Continents",continents_path,:class => "button circled scroll"%>
</div>

app/views/locations/new.html.erb
<div class="container">
<%= simple_form_for @location do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
   <%= f.input :address %>
  <%=f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/surfcamps/index.html.erb
<div class="banner">
  <%if @location.photo.attached?%>
  <%=image_tag @location.photo%>
  <%end%>
</div>

<h3><%=@location.name%></h3>

<div>
<%@surfcamps.each do |surfcamp|%>
<%=surfcamp.name%>
<%end%>
</div>

<div class="text-center">
<%=link_to "Create new Surfcamp",new_continent_location_surfcamp_path(@continent,@location),:class => "button circled scroll"%>
<%=link_to "Go to Continents",continents_path,:class => "button circled scroll"%>
</div>

app/views/surfcamps/new.html.erb
<div class="container">
<%= simple_form_for ([@continent,@location,@surfcamp])  do |f|%>
  <%= f.input :name %>
  <%= f.input :stars %>
  <%= f.input :price %>
  <%= f.input :address %>
  <%=f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/surfcamps/show.html.erb
<div class="banner">
  <%if @location.photo.attached?%>
  <%=image_tag @location.photo%>
  <%end%>
</div>

<h3><%=@location.name%></h3>